services:
  robomind:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
    volumes:
      - ./robomind:/app/robomind
    environment:
      - PYTHONUNBUFFERED=1

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

volumes:
  redis_data: